### ISSUE TITLE
[webp] TypeError: Missing field

### ISSUE THREAD

**Issue by s-h-a-d-o-w** [saschazar21/webassembly#1]
Using the example from your `README`, I get:

```
TypeError: Missing field
TypeError: Missing field
C:\Users\sh4dow\development\temp\wasm-webp\node_modules\@saschazar\wasm-webp\wasm_webp.js:9
var Module=typeof wasm_webp!=="undefined"?wasm_webp:{};var moduleOverrides={};var key;for(key in Module){if(Module.hasOwnProperty(key)){moduleOverrides[key]=Module[key]}}var arguments_=[];var thisProgram="./this.program";var quit_=function(status,toThrow){throw toThrow};var ENVIRONMENT_IS_WEB=false;var ENVIRONMENT_IS_WORKER=false;var ENVIRONMENT_IS_NODE=false;var ENVIRONMENT_HAS_NODE=false;var ENVIRONMENT_IS_SHELL=false;ENVIRONMENT_IS_WEB=typeof window==="object";ENVIRONMENT_IS_WORKER=typeof importScripts==="function";ENVIRONMENT_HAS_NODE=typeof process==="object"&&typeof process.versions==="object"&&typeof process.versions.node==="string";ENVIRONMENT_IS_NODE=ENVIRONMENT_HAS_NODE&&!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_WORKER;ENVIRONMENT_IS_SHELL=!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_NODE&&!ENVIRONMENT_IS_WORKER;var scriptDirectory="";function locateFile(path){if(Module["locateFile"]){return Module["locateFile"](path,sc

RuntimeError: abort(TypeError: Missing field). Build with -s ASSERTIONS=1 for more info.
    at process.abort (C:\Users\sh4dow\development\temp\wasm-webp\node_modules\@saschazar\wasm-webp\wasm_webp.js:9:9577)
    at process.emit (events.js:210:5)
    at processPromiseRejections (internal/process/promises.js:201:33)
    at processTicksAndRejections (internal/process/task_queues.js:94:32)
```

**Comment by saschazar21** [comment]
Hi @s-h-a-d-o-w - have you tried to use the options provided as default export in `options.js`?

As far as I know, `webp` crucially needs to have all option parameters populated (just as in the default options), otherwise it likely throws errors.

I will have a look myself and update the `README.md` accordingly, if I find something...

**Comment by saschazar21** [comment]
After some investigations I can tell, that the example in the `README` is fully working (after applying a few tweaks to get async/await properly going).

However, as I mentioned above, a fully populated options object is crucial in this case.

An interactive code example is available on Runkit: https://runkit.com/saschazar21/5e8713b993ce6a00127b183b

**Comment by s-h-a-d-o-w** [comment]
Thanks, the problem was the options object!

I'd recommend to do one of the following:
- Use the default options object internally (don't export it) and the options object supplied by the user as an override that is merged. (And somehow make the user more directly aware of the options available - either pasting the default values in the usage code or by linking to `options.js` or the libwebp docs.)
- Get rid of the "to gain the best possible outcome" in the `README` and don't let the native code fail horribly but check whether a complete options object was supplied and print a comprehensible error message if that wasn't the case. 😉

**Comment by saschazar21** [comment]
Glad it solved your issue.

Will try to work on rephrasing the `README` over the next days.

Since the JavaScript bindings are generated by [Emscripten](https://emscripten.org/), I currently don't see a way of including proper error handling, other than wrapping a custom JavaScript API around it, or custom-loading the `.wasm` file.

Both possibilities are currently out of scope for me, but if you'd like to contribute, a PR is always welcome!

As I reckon your issue is solved for now, I will close this issue over the next few days.
