### ISSUE TITLE
webp  support animation?

### ISSUE THREAD

**Issue by 3400442579** [saschazar21/webassembly#373]
webp  support animation?

**Comment by saschazar21** [comment]
Hi @3400442579 - there are currently no plans to support `webp` animation within this repository. This is due to mainly one reason; every frame has to be stored as raw RGBA buffer in-memory before being encoded to `webp`.

Since this action is likely to cause unforeseeable memory issues, I see no real use case to port it to WebAssembly.

But of course, I'd definitely appreciate a PR for this topic if someone wants to dig further...
